# Generated by Django 5.0 on 2023-12-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
    ]
