# Generated by Django 5.0 on 2023-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvApp', '0002_remove_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='high_school',
            field=models.CharField(default='Not finished', max_length=255),
        ),
    ]
